### ISSUE TITLE
Variable in blockfactory

### ISSUE THREAD

**Issue by tchichi** [UCL-INGI/INGInious-problems-blockly#10]
When rightclicking on "set _variable_ to",

- in the blockfactory of google:
![good](https://user-images.githubusercontent.com/20316317/42323538-d39402c0-8060-11e8-8eea-73785ca5a638.png)

- in our blockfactory:
![bad](https://user-images.githubusercontent.com/20316317/42323564-eb25e82c-8060-11e8-8850-c29680499c3d.png)
This creates a new variable with the identifier as the name

**Comment by ogoletti** [comment]
Hi, 

Idd "our" blockfactory is outdated !

It should be replaced by : https://github.com/google/blockly/tree/7679d227df8f62a12316334ee708d4a9a800ef17/demos/blockfactory

I don't know why it's not in sync with that code. It should be. 

Please use https://blockly-demo.appspot.com/static/demos/blockfactory/index.html to create custom blocks/toolboxes/workspace content at the moment and export the generated xml in your task.

**Comment by ogoletti** [comment]
This issue will be solved with https://github.com/UCL-INGI/INGInious-problems-blockly/issues/15
